import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const Material=z.object({id:z.string().uuid().optional(),code:z.string().trim().max(100).nullable().optional(),name:z.string().trim().min(1).max(200),unit:z.string().trim().min(1).max(30),reorder_level:z.number().finite().nonnegative(),notes:z.string().trim().max(5000).nullable().optional()});
const Recipe=z.object({raw_material_id:z.string().uuid(),quantity_per_unit:z.number().finite().positive()});
const Model=z.object({id:z.string().uuid().optional(),code:z.string().trim().max(100).nullable().optional(),name:z.string().trim().min(1).max(200),size:z.string().trim().max(100).nullable().optional(),thickness:z.string().trim().max(100).nullable().optional(),cover_fabric:z.string().trim().max(200).nullable().optional(),foam_density:z.string().trim().max(100).nullable().optional(),warranty:z.string().trim().max(200).nullable().optional(),default_price:z.number().finite().nonnegative(),extra_specs:z.record(z.string(),z.string()).default({}),notes:z.string().trim().max(5000).nullable().optional(),recipe:z.array(Recipe).min(1).max(200)});
async function roles(db:any,userId:string,allowed:string[]){const {data}=await db.from("user_roles").select("role").eq("user_id",userId).in("role",allowed);if(!data?.length)throw new Error("Insufficient permissions");}
export const saveRawMaterial=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>Material.parse(d)).handler(async({data,context})=>{
 await roles(context.supabase,context.userId,["admin","production"]); const {data:company,error}=await context.supabase.rpc("current_company_id");if(error||!company)throw new Error("No active company selected");
 if(data.id){const {error:e}=await context.supabase.from("raw_materials").update({code:data.code??null,name:data.name,unit:data.unit,reorder_level:data.reorder_level,notes:data.notes??null}).eq("id",data.id).eq("company_id",company);if(e)throw new Error(e.message);return{id:data.id};}
 const {data:r,error:e}=await context.supabase.from("raw_materials").insert({company_id:company,code:data.code??null,name:data.name,unit:data.unit,reorder_level:data.reorder_level,notes:data.notes??null}).select("id").single();if(e||!r)throw new Error(e?.message??"Failed to save raw material");return{id:r.id};
});
export const saveProductModel=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>Model.parse(d)).handler(async({data,context})=>{
 await roles(context.supabase,context.userId,["admin","sales","production"]);const {data:company,error}=await context.supabase.rpc("current_company_id");if(error||!company)throw new Error("No active company selected");
 const ids=[...new Set(data.recipe.map(x=>x.raw_material_id))];const {data:materials,error:me}=await context.supabase.from("raw_materials").select("id").in("id",ids).eq("company_id",company);if(me)throw new Error(me.message);if((materials??[]).length!==ids.length)throw new Error("BOQ contains a raw material outside the active company");
 let modelId=data.id;
 if(modelId){const {error:e}=await context.supabase.from("product_models").update({code:data.code??null,name:data.name,size:data.size??null,thickness:data.thickness??null,cover_fabric:data.cover_fabric??null,foam_density:data.foam_density??null,warranty:data.warranty??null,default_price:data.default_price,extra_specs:data.extra_specs,notes:data.notes??null}).eq("id",modelId).eq("company_id",company);if(e)throw new Error(e.message);await context.supabase.from("model_boq").delete().eq("model_id",modelId).eq("company_id",company);}
 else {const {data:m,error:e}=await context.supabase.from("product_models").insert({company_id:company,code:data.code??null,name:data.name,size:data.size??null,thickness:data.thickness??null,cover_fabric:data.cover_fabric??null,foam_density:data.foam_density??null,warranty:data.warranty??null,default_price:data.default_price,extra_specs:data.extra_specs,notes:data.notes??null}).select("id").single();if(e||!m)throw new Error(e?.message??"Failed to save model");modelId=m.id;}
 const {error:be}=await context.supabase.from("model_boq").insert(data.recipe.map(x=>({company_id:company,model_id:modelId,raw_material_id:x.raw_material_id,quantity_per_unit:x.quantity_per_unit})));if(be)throw new Error(be.message);return{id:modelId};
});
