import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
const S=z.object({id:z.string().uuid().optional(),employee_code:z.string().trim().min(1).max(50),full_name:z.string().trim().min(1).max(200),email:z.string().email().max(320).nullable().optional(),phone:z.string().trim().max(30).nullable().optional(),department:z.string().trim().max(100).nullable().optional(),designation:z.string().trim().max(100).nullable().optional(),date_of_joining:z.string().nullable().optional(),pay_type:z.string().trim().max(30),basic_salary:z.number().finite().nonnegative(),da:z.number().finite().nonnegative(),hra:z.number().finite().nonnegative(),other_allowances:z.number().finite().nonnegative(),daily_wage:z.number().finite().nonnegative(),ot_rate_per_hour:z.number().finite().nonnegative(),pf_deduction:z.number().finite().nonnegative(),esi_deduction:z.number().finite().nonnegative(),is_active:z.boolean()});
export const saveEmployee=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator(d=>S.parse(d)).handler(async({data,context})=>{
 const {data:roles}=await context.supabase.from("user_roles").select("role").eq("user_id",context.userId).in("role",["admin","hr"]);if(!roles?.length)throw new Error("Insufficient permissions");
 const {data:company,error}=await context.supabase.rpc("current_company_id");if(error||!company)throw new Error("No active company selected");
 const payload={company_id:company,employee_code:data.employee_code,full_name:data.full_name,email:data.email??null,phone:data.phone??null,department:data.department??null,designation:data.designation??null,date_of_joining:data.date_of_joining??null,pay_type:data.pay_type,basic_salary:data.basic_salary,da:data.da,hra:data.hra,other_allowances:data.other_allowances,daily_wage:data.daily_wage,ot_rate_per_hour:data.ot_rate_per_hour,pf_deduction:data.pf_deduction,esi_deduction:data.esi_deduction,is_active:data.is_active};
 if(data.id){const {error:e}=await context.supabase.from("employees").update(payload).eq("id",data.id).eq("company_id",company);if(e)throw new Error(e.message);return{id:data.id};}
 const {data:r,error:e}=await context.supabase.from("employees").insert(payload).select("id").single();if(e||!r)throw new Error(e?.message??"Failed to save employee");return{id:r.id};
});
