/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorSignupRouteImport } from './routes/vendor-signup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppVendorRouteImport } from './routes/_app.vendor'
import { Route as AppTallyImportRouteImport } from './routes/_app.tally-import'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesOrdersRouteImport } from './routes/_app.sales-orders'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppProductionRouteImport } from './routes/_app.production'
import { Route as AppPayslipsRouteImport } from './routes/_app.payslips'
import { Route as AppPartiesRouteImport } from './routes/_app.parties'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppGstRouteImport } from './routes/_app.gst'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunicationsRouteImport } from './routes/_app.communications'
import { Route as AppBoqRouteImport } from './routes/_app.boq'
import { Route as AppBankingRouteImport } from './routes/_app.banking'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as AppVendorIndexRouteImport } from './routes/_app.vendor.index'
import { Route as AppCommunicationsIndexRouteImport } from './routes/_app.communications.index'
import { Route as AppVendorPurchaseOrdersRouteImport } from './routes/_app.vendor.purchase-orders'
import { Route as AppVendorLedgerRouteImport } from './routes/_app.vendor.ledger'
import { Route as AppInventoryValuationRouteImport } from './routes/_app.inventory.valuation'
import { Route as AppInventorySummaryRouteImport } from './routes/_app.inventory.summary'
import { Route as AppInventoryReorderRouteImport } from './routes/_app.inventory.reorder'
import { Route as AppInventoryMovementsRouteImport } from './routes/_app.inventory.movements'
import { Route as AppInventoryJournalsRouteImport } from './routes/_app.inventory.journals'
import { Route as AppInventoryItemsRouteImport } from './routes/_app.inventory.items'
import { Route as AppInventoryGodownsRouteImport } from './routes/_app.inventory.godowns'
import { Route as AppGstReturnsRouteImport } from './routes/_app.gst.returns'
import { Route as AppGstHsnRouteImport } from './routes/_app.gst.hsn'
import { Route as AppGstEinvoicesRouteImport } from './routes/_app.gst.einvoices'
import { Route as AppCommunicationsWhatsappLogsRouteImport } from './routes/_app.communications.whatsapp-logs'
import { Route as AppCommunicationsTemplatesRouteImport } from './routes/_app.communications.templates'
import { Route as AppCommunicationsProvidersRouteImport } from './routes/_app.communications.providers'
import { Route as AppBankingReconcileRouteImport } from './routes/_app.banking.reconcile'
import { Route as AppBankingPaymentAdviceRouteImport } from './routes/_app.banking.payment-advice'
import { Route as AppBankingCurrenciesRouteImport } from './routes/_app.banking.currencies'
import { Route as AppBankingChequesRouteImport } from './routes/_app.banking.cheques'
import { Route as AppBankingAccountsRouteImport } from './routes/_app.banking.accounts'
import { Route as AppAccountingTrialBalanceRouteImport } from './routes/_app.accounting.trial-balance'
import { Route as AppAccountingProfitLossRouteImport } from './routes/_app.accounting.profit-loss'
import { Route as AppAccountingPeriodsRouteImport } from './routes/_app.accounting.periods'
import { Route as AppAccountingLedgersRouteImport } from './routes/_app.accounting.ledgers'
import { Route as AppAccountingDayBookRouteImport } from './routes/_app.accounting.day-book'
import { Route as AppAccountingBalanceSheetRouteImport } from './routes/_app.accounting.balance-sheet'
import { Route as AppAccountingAuditLogRouteImport } from './routes/_app.accounting.audit-log'
import { Route as ApiPublicWhatsappInteraktRouteImport } from './routes/api/public/whatsapp/interakt'
import { Route as ApiPublicBiometricPunchRouteImport } from './routes/api/public/biometric/punch'
import { Route as AppVendorPurchaseOrdersIdRouteImport } from './routes/_app.vendor.purchase-orders.$id'
import { Route as AppPrintSupplierLedgerIdRouteImport } from './routes/_app.print.supplier-ledger.$id'
import { Route as AppPrintPurchaseIdRouteImport } from './routes/_app.print.purchase.$id'
import { Route as AppPrintPartyLedgerIdRouteImport } from './routes/_app.print.party-ledger.$id'
import { Route as AppPrintInvoiceIdRouteImport } from './routes/_app.print.invoice.$id'
import { Route as AppGstReturnsIdRouteImport } from './routes/_app.gst.returns.$id'
import { Route as AppBankingReconcileIdRouteImport } from './routes/_app.banking.reconcile.$id'
import { Route as AppBankingChequePrintIdRouteImport } from './routes/_app.banking.cheque-print.$id'
import { Route as AppAccountingVouchersNewRouteImport } from './routes/_app.accounting.vouchers.new'
import { Route as AppAccountingVoucherIdRouteImport } from './routes/_app.accounting.voucher.$id'
import { Route as AppAccountingLedgerIdRouteImport } from './routes/_app.accounting.ledger.$id'

const VendorSignupRoute = VendorSignupRouteImport.update({
  id: '/vendor-signup',
  path: '/vendor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorRoute = AppVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AppRoute,
} as any)
const AppTallyImportRoute = AppTallyImportRouteImport.update({
  id: '/tally-import',
  path: '/tally-import',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPayslipsRoute = AppPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGstRoute = AppGstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)
const AppBoqRoute = AppBoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => AppRoute,
} as any)
const AppBankingRoute = AppBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorIndexRoute = AppVendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppCommunicationsIndexRoute = AppCommunicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCommunicationsRoute,
} as any)
const AppVendorPurchaseOrdersRoute = AppVendorPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorLedgerRoute = AppVendorLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppInventoryValuationRoute = AppInventoryValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventorySummaryRoute = AppInventorySummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryReorderRoute = AppInventoryReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryJournalsRoute = AppInventoryJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryItemsRoute = AppInventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryGodownsRoute = AppInventoryGodownsRouteImport.update({
  id: '/godowns',
  path: '/godowns',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppGstReturnsRoute = AppGstReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppGstRoute,
} as any)
const AppGstHsnRoute = AppGstHsnRouteImport.update({
  id: '/hsn',
  path: '/hsn',
  getParentRoute: () => AppGstRoute,
} as any)
const AppGstEinvoicesRoute = AppGstEinvoicesRouteImport.update({
  id: '/einvoices',
  path: '/einvoices',
  getParentRoute: () => AppGstRoute,
} as any)
const AppCommunicationsWhatsappLogsRoute =
  AppCommunicationsWhatsappLogsRouteImport.update({
    id: '/whatsapp-logs',
    path: '/whatsapp-logs',
    getParentRoute: () => AppCommunicationsRoute,
  } as any)
const AppCommunicationsTemplatesRoute =
  AppCommunicationsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppCommunicationsRoute,
  } as any)
const AppCommunicationsProvidersRoute =
  AppCommunicationsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppCommunicationsRoute,
  } as any)
const AppBankingReconcileRoute = AppBankingReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => AppBankingRoute,
} as any)
const AppBankingPaymentAdviceRoute = AppBankingPaymentAdviceRouteImport.update({
  id: '/payment-advice',
  path: '/payment-advice',
  getParentRoute: () => AppBankingRoute,
} as any)
const AppBankingCurrenciesRoute = AppBankingCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AppBankingRoute,
} as any)
const AppBankingChequesRoute = AppBankingChequesRouteImport.update({
  id: '/cheques',
  path: '/cheques',
  getParentRoute: () => AppBankingRoute,
} as any)
const AppBankingAccountsRoute = AppBankingAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppBankingRoute,
} as any)
const AppAccountingTrialBalanceRoute =
  AppAccountingTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AppAccountingRoute,
  } as any)
const AppAccountingProfitLossRoute = AppAccountingProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingPeriodsRoute = AppAccountingPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingLedgersRoute = AppAccountingLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingDayBookRoute = AppAccountingDayBookRouteImport.update({
  id: '/day-book',
  path: '/day-book',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingBalanceSheetRoute =
  AppAccountingBalanceSheetRouteImport.update({
    id: '/balance-sheet',
    path: '/balance-sheet',
    getParentRoute: () => AppAccountingRoute,
  } as any)
const AppAccountingAuditLogRoute = AppAccountingAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppAccountingRoute,
} as any)
const ApiPublicWhatsappInteraktRoute =
  ApiPublicWhatsappInteraktRouteImport.update({
    id: '/api/public/whatsapp/interakt',
    path: '/api/public/whatsapp/interakt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBiometricPunchRoute = ApiPublicBiometricPunchRouteImport.update({
  id: '/api/public/biometric/punch',
  path: '/api/public/biometric/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorPurchaseOrdersIdRoute =
  AppVendorPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppVendorPurchaseOrdersRoute,
  } as any)
const AppPrintSupplierLedgerIdRoute =
  AppPrintSupplierLedgerIdRouteImport.update({
    id: '/print/supplier-ledger/$id',
    path: '/print/supplier-ledger/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppPrintPurchaseIdRoute = AppPrintPurchaseIdRouteImport.update({
  id: '/print/purchase/$id',
  path: '/print/purchase/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintPartyLedgerIdRoute = AppPrintPartyLedgerIdRouteImport.update({
  id: '/print/party-ledger/$id',
  path: '/print/party-ledger/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintInvoiceIdRoute = AppPrintInvoiceIdRouteImport.update({
  id: '/print/invoice/$id',
  path: '/print/invoice/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGstReturnsIdRoute = AppGstReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGstReturnsRoute,
} as any)
const AppBankingReconcileIdRoute = AppBankingReconcileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBankingReconcileRoute,
} as any)
const AppBankingChequePrintIdRoute = AppBankingChequePrintIdRouteImport.update({
  id: '/cheque-print/$id',
  path: '/cheque-print/$id',
  getParentRoute: () => AppBankingRoute,
} as any)
const AppAccountingVouchersNewRoute =
  AppAccountingVouchersNewRouteImport.update({
    id: '/vouchers/new',
    path: '/vouchers/new',
    getParentRoute: () => AppAccountingRoute,
  } as any)
const AppAccountingVoucherIdRoute = AppAccountingVoucherIdRouteImport.update({
  id: '/voucher/$id',
  path: '/voucher/$id',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppAccountingLedgerIdRoute = AppAccountingLedgerIdRouteImport.update({
  id: '/ledger/$id',
  path: '/ledger/$id',
  getParentRoute: () => AppAccountingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/accounting': typeof AppAccountingRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/attendance': typeof AppAttendanceRoute
  '/banking': typeof AppBankingRouteWithChildren
  '/boq': typeof AppBoqRoute
  '/communications': typeof AppCommunicationsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/gst': typeof AppGstRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRoute
  '/parties': typeof AppPartiesRoute
  '/payslips': typeof AppPayslipsRoute
  '/production': typeof AppProductionRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales-orders': typeof AppSalesOrdersRoute
  '/settings': typeof AppSettingsRoute
  '/tally-import': typeof AppTallyImportRoute
  '/vendor': typeof AppVendorRouteWithChildren
  '/whatsapp': typeof AppWhatsappRoute
  '/accounting/audit-log': typeof AppAccountingAuditLogRoute
  '/accounting/balance-sheet': typeof AppAccountingBalanceSheetRoute
  '/accounting/day-book': typeof AppAccountingDayBookRoute
  '/accounting/ledgers': typeof AppAccountingLedgersRoute
  '/accounting/periods': typeof AppAccountingPeriodsRoute
  '/accounting/profit-loss': typeof AppAccountingProfitLossRoute
  '/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/banking/accounts': typeof AppBankingAccountsRoute
  '/banking/cheques': typeof AppBankingChequesRoute
  '/banking/currencies': typeof AppBankingCurrenciesRoute
  '/banking/payment-advice': typeof AppBankingPaymentAdviceRoute
  '/banking/reconcile': typeof AppBankingReconcileRouteWithChildren
  '/communications/providers': typeof AppCommunicationsProvidersRoute
  '/communications/templates': typeof AppCommunicationsTemplatesRoute
  '/communications/whatsapp-logs': typeof AppCommunicationsWhatsappLogsRoute
  '/gst/einvoices': typeof AppGstEinvoicesRoute
  '/gst/hsn': typeof AppGstHsnRoute
  '/gst/returns': typeof AppGstReturnsRouteWithChildren
  '/inventory/godowns': typeof AppInventoryGodownsRoute
  '/inventory/items': typeof AppInventoryItemsRoute
  '/inventory/journals': typeof AppInventoryJournalsRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/reorder': typeof AppInventoryReorderRoute
  '/inventory/summary': typeof AppInventorySummaryRoute
  '/inventory/valuation': typeof AppInventoryValuationRoute
  '/vendor/ledger': typeof AppVendorLedgerRoute
  '/vendor/purchase-orders': typeof AppVendorPurchaseOrdersRouteWithChildren
  '/communications/': typeof AppCommunicationsIndexRoute
  '/vendor/': typeof AppVendorIndexRoute
  '/accounting/ledger/$id': typeof AppAccountingLedgerIdRoute
  '/accounting/voucher/$id': typeof AppAccountingVoucherIdRoute
  '/accounting/vouchers/new': typeof AppAccountingVouchersNewRoute
  '/banking/cheque-print/$id': typeof AppBankingChequePrintIdRoute
  '/banking/reconcile/$id': typeof AppBankingReconcileIdRoute
  '/gst/returns/$id': typeof AppGstReturnsIdRoute
  '/print/invoice/$id': typeof AppPrintInvoiceIdRoute
  '/print/party-ledger/$id': typeof AppPrintPartyLedgerIdRoute
  '/print/purchase/$id': typeof AppPrintPurchaseIdRoute
  '/print/supplier-ledger/$id': typeof AppPrintSupplierLedgerIdRoute
  '/vendor/purchase-orders/$id': typeof AppVendorPurchaseOrdersIdRoute
  '/api/public/biometric/punch': typeof ApiPublicBiometricPunchRoute
  '/api/public/whatsapp/interakt': typeof ApiPublicWhatsappInteraktRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/accounting': typeof AppAccountingRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/attendance': typeof AppAttendanceRoute
  '/banking': typeof AppBankingRouteWithChildren
  '/boq': typeof AppBoqRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/gst': typeof AppGstRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRoute
  '/parties': typeof AppPartiesRoute
  '/payslips': typeof AppPayslipsRoute
  '/production': typeof AppProductionRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales-orders': typeof AppSalesOrdersRoute
  '/settings': typeof AppSettingsRoute
  '/tally-import': typeof AppTallyImportRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/accounting/audit-log': typeof AppAccountingAuditLogRoute
  '/accounting/balance-sheet': typeof AppAccountingBalanceSheetRoute
  '/accounting/day-book': typeof AppAccountingDayBookRoute
  '/accounting/ledgers': typeof AppAccountingLedgersRoute
  '/accounting/periods': typeof AppAccountingPeriodsRoute
  '/accounting/profit-loss': typeof AppAccountingProfitLossRoute
  '/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/banking/accounts': typeof AppBankingAccountsRoute
  '/banking/cheques': typeof AppBankingChequesRoute
  '/banking/currencies': typeof AppBankingCurrenciesRoute
  '/banking/payment-advice': typeof AppBankingPaymentAdviceRoute
  '/banking/reconcile': typeof AppBankingReconcileRouteWithChildren
  '/communications/providers': typeof AppCommunicationsProvidersRoute
  '/communications/templates': typeof AppCommunicationsTemplatesRoute
  '/communications/whatsapp-logs': typeof AppCommunicationsWhatsappLogsRoute
  '/gst/einvoices': typeof AppGstEinvoicesRoute
  '/gst/hsn': typeof AppGstHsnRoute
  '/gst/returns': typeof AppGstReturnsRouteWithChildren
  '/inventory/godowns': typeof AppInventoryGodownsRoute
  '/inventory/items': typeof AppInventoryItemsRoute
  '/inventory/journals': typeof AppInventoryJournalsRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/reorder': typeof AppInventoryReorderRoute
  '/inventory/summary': typeof AppInventorySummaryRoute
  '/inventory/valuation': typeof AppInventoryValuationRoute
  '/vendor/ledger': typeof AppVendorLedgerRoute
  '/vendor/purchase-orders': typeof AppVendorPurchaseOrdersRouteWithChildren
  '/communications': typeof AppCommunicationsIndexRoute
  '/vendor': typeof AppVendorIndexRoute
  '/accounting/ledger/$id': typeof AppAccountingLedgerIdRoute
  '/accounting/voucher/$id': typeof AppAccountingVoucherIdRoute
  '/accounting/vouchers/new': typeof AppAccountingVouchersNewRoute
  '/banking/cheque-print/$id': typeof AppBankingChequePrintIdRoute
  '/banking/reconcile/$id': typeof AppBankingReconcileIdRoute
  '/gst/returns/$id': typeof AppGstReturnsIdRoute
  '/print/invoice/$id': typeof AppPrintInvoiceIdRoute
  '/print/party-ledger/$id': typeof AppPrintPartyLedgerIdRoute
  '/print/purchase/$id': typeof AppPrintPurchaseIdRoute
  '/print/supplier-ledger/$id': typeof AppPrintSupplierLedgerIdRoute
  '/vendor/purchase-orders/$id': typeof AppVendorPurchaseOrdersIdRoute
  '/api/public/biometric/punch': typeof ApiPublicBiometricPunchRoute
  '/api/public/whatsapp/interakt': typeof ApiPublicWhatsappInteraktRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/vendor-signup': typeof VendorSignupRoute
  '/_app/accounting': typeof AppAccountingRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/banking': typeof AppBankingRouteWithChildren
  '/_app/boq': typeof AppBoqRoute
  '/_app/communications': typeof AppCommunicationsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/gst': typeof AppGstRouteWithChildren
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/parties': typeof AppPartiesRoute
  '/_app/payslips': typeof AppPayslipsRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/sales-orders': typeof AppSalesOrdersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tally-import': typeof AppTallyImportRoute
  '/_app/vendor': typeof AppVendorRouteWithChildren
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/accounting/audit-log': typeof AppAccountingAuditLogRoute
  '/_app/accounting/balance-sheet': typeof AppAccountingBalanceSheetRoute
  '/_app/accounting/day-book': typeof AppAccountingDayBookRoute
  '/_app/accounting/ledgers': typeof AppAccountingLedgersRoute
  '/_app/accounting/periods': typeof AppAccountingPeriodsRoute
  '/_app/accounting/profit-loss': typeof AppAccountingProfitLossRoute
  '/_app/accounting/trial-balance': typeof AppAccountingTrialBalanceRoute
  '/_app/banking/accounts': typeof AppBankingAccountsRoute
  '/_app/banking/cheques': typeof AppBankingChequesRoute
  '/_app/banking/currencies': typeof AppBankingCurrenciesRoute
  '/_app/banking/payment-advice': typeof AppBankingPaymentAdviceRoute
  '/_app/banking/reconcile': typeof AppBankingReconcileRouteWithChildren
  '/_app/communications/providers': typeof AppCommunicationsProvidersRoute
  '/_app/communications/templates': typeof AppCommunicationsTemplatesRoute
  '/_app/communications/whatsapp-logs': typeof AppCommunicationsWhatsappLogsRoute
  '/_app/gst/einvoices': typeof AppGstEinvoicesRoute
  '/_app/gst/hsn': typeof AppGstHsnRoute
  '/_app/gst/returns': typeof AppGstReturnsRouteWithChildren
  '/_app/inventory/godowns': typeof AppInventoryGodownsRoute
  '/_app/inventory/items': typeof AppInventoryItemsRoute
  '/_app/inventory/journals': typeof AppInventoryJournalsRoute
  '/_app/inventory/movements': typeof AppInventoryMovementsRoute
  '/_app/inventory/reorder': typeof AppInventoryReorderRoute
  '/_app/inventory/summary': typeof AppInventorySummaryRoute
  '/_app/inventory/valuation': typeof AppInventoryValuationRoute
  '/_app/vendor/ledger': typeof AppVendorLedgerRoute
  '/_app/vendor/purchase-orders': typeof AppVendorPurchaseOrdersRouteWithChildren
  '/_app/communications/': typeof AppCommunicationsIndexRoute
  '/_app/vendor/': typeof AppVendorIndexRoute
  '/_app/accounting/ledger/$id': typeof AppAccountingLedgerIdRoute
  '/_app/accounting/voucher/$id': typeof AppAccountingVoucherIdRoute
  '/_app/accounting/vouchers/new': typeof AppAccountingVouchersNewRoute
  '/_app/banking/cheque-print/$id': typeof AppBankingChequePrintIdRoute
  '/_app/banking/reconcile/$id': typeof AppBankingReconcileIdRoute
  '/_app/gst/returns/$id': typeof AppGstReturnsIdRoute
  '/_app/print/invoice/$id': typeof AppPrintInvoiceIdRoute
  '/_app/print/party-ledger/$id': typeof AppPrintPartyLedgerIdRoute
  '/_app/print/purchase/$id': typeof AppPrintPurchaseIdRoute
  '/_app/print/supplier-ledger/$id': typeof AppPrintSupplierLedgerIdRoute
  '/_app/vendor/purchase-orders/$id': typeof AppVendorPurchaseOrdersIdRoute
  '/api/public/biometric/punch': typeof ApiPublicBiometricPunchRoute
  '/api/public/whatsapp/interakt': typeof ApiPublicWhatsappInteraktRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/vendor-signup'
    | '/accounting'
    | '/approvals'
    | '/attendance'
    | '/banking'
    | '/boq'
    | '/communications'
    | '/dashboard'
    | '/employees'
    | '/gst'
    | '/inventory'
    | '/invoices'
    | '/parties'
    | '/payslips'
    | '/production'
    | '/purchases'
    | '/sales-orders'
    | '/settings'
    | '/tally-import'
    | '/vendor'
    | '/whatsapp'
    | '/accounting/audit-log'
    | '/accounting/balance-sheet'
    | '/accounting/day-book'
    | '/accounting/ledgers'
    | '/accounting/periods'
    | '/accounting/profit-loss'
    | '/accounting/trial-balance'
    | '/banking/accounts'
    | '/banking/cheques'
    | '/banking/currencies'
    | '/banking/payment-advice'
    | '/banking/reconcile'
    | '/communications/providers'
    | '/communications/templates'
    | '/communications/whatsapp-logs'
    | '/gst/einvoices'
    | '/gst/hsn'
    | '/gst/returns'
    | '/inventory/godowns'
    | '/inventory/items'
    | '/inventory/journals'
    | '/inventory/movements'
    | '/inventory/reorder'
    | '/inventory/summary'
    | '/inventory/valuation'
    | '/vendor/ledger'
    | '/vendor/purchase-orders'
    | '/communications/'
    | '/vendor/'
    | '/accounting/ledger/$id'
    | '/accounting/voucher/$id'
    | '/accounting/vouchers/new'
    | '/banking/cheque-print/$id'
    | '/banking/reconcile/$id'
    | '/gst/returns/$id'
    | '/print/invoice/$id'
    | '/print/party-ledger/$id'
    | '/print/purchase/$id'
    | '/print/supplier-ledger/$id'
    | '/vendor/purchase-orders/$id'
    | '/api/public/biometric/punch'
    | '/api/public/whatsapp/interakt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/vendor-signup'
    | '/accounting'
    | '/approvals'
    | '/attendance'
    | '/banking'
    | '/boq'
    | '/dashboard'
    | '/employees'
    | '/gst'
    | '/inventory'
    | '/invoices'
    | '/parties'
    | '/payslips'
    | '/production'
    | '/purchases'
    | '/sales-orders'
    | '/settings'
    | '/tally-import'
    | '/whatsapp'
    | '/accounting/audit-log'
    | '/accounting/balance-sheet'
    | '/accounting/day-book'
    | '/accounting/ledgers'
    | '/accounting/periods'
    | '/accounting/profit-loss'
    | '/accounting/trial-balance'
    | '/banking/accounts'
    | '/banking/cheques'
    | '/banking/currencies'
    | '/banking/payment-advice'
    | '/banking/reconcile'
    | '/communications/providers'
    | '/communications/templates'
    | '/communications/whatsapp-logs'
    | '/gst/einvoices'
    | '/gst/hsn'
    | '/gst/returns'
    | '/inventory/godowns'
    | '/inventory/items'
    | '/inventory/journals'
    | '/inventory/movements'
    | '/inventory/reorder'
    | '/inventory/summary'
    | '/inventory/valuation'
    | '/vendor/ledger'
    | '/vendor/purchase-orders'
    | '/communications'
    | '/vendor'
    | '/accounting/ledger/$id'
    | '/accounting/voucher/$id'
    | '/accounting/vouchers/new'
    | '/banking/cheque-print/$id'
    | '/banking/reconcile/$id'
    | '/gst/returns/$id'
    | '/print/invoice/$id'
    | '/print/party-ledger/$id'
    | '/print/purchase/$id'
    | '/print/supplier-ledger/$id'
    | '/vendor/purchase-orders/$id'
    | '/api/public/biometric/punch'
    | '/api/public/whatsapp/interakt'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/vendor-signup'
    | '/_app/accounting'
    | '/_app/approvals'
    | '/_app/attendance'
    | '/_app/banking'
    | '/_app/boq'
    | '/_app/communications'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/gst'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/parties'
    | '/_app/payslips'
    | '/_app/production'
    | '/_app/purchases'
    | '/_app/sales-orders'
    | '/_app/settings'
    | '/_app/tally-import'
    | '/_app/vendor'
    | '/_app/whatsapp'
    | '/_app/accounting/audit-log'
    | '/_app/accounting/balance-sheet'
    | '/_app/accounting/day-book'
    | '/_app/accounting/ledgers'
    | '/_app/accounting/periods'
    | '/_app/accounting/profit-loss'
    | '/_app/accounting/trial-balance'
    | '/_app/banking/accounts'
    | '/_app/banking/cheques'
    | '/_app/banking/currencies'
    | '/_app/banking/payment-advice'
    | '/_app/banking/reconcile'
    | '/_app/communications/providers'
    | '/_app/communications/templates'
    | '/_app/communications/whatsapp-logs'
    | '/_app/gst/einvoices'
    | '/_app/gst/hsn'
    | '/_app/gst/returns'
    | '/_app/inventory/godowns'
    | '/_app/inventory/items'
    | '/_app/inventory/journals'
    | '/_app/inventory/movements'
    | '/_app/inventory/reorder'
    | '/_app/inventory/summary'
    | '/_app/inventory/valuation'
    | '/_app/vendor/ledger'
    | '/_app/vendor/purchase-orders'
    | '/_app/communications/'
    | '/_app/vendor/'
    | '/_app/accounting/ledger/$id'
    | '/_app/accounting/voucher/$id'
    | '/_app/accounting/vouchers/new'
    | '/_app/banking/cheque-print/$id'
    | '/_app/banking/reconcile/$id'
    | '/_app/gst/returns/$id'
    | '/_app/print/invoice/$id'
    | '/_app/print/party-ledger/$id'
    | '/_app/print/purchase/$id'
    | '/_app/print/supplier-ledger/$id'
    | '/_app/vendor/purchase-orders/$id'
    | '/api/public/biometric/punch'
    | '/api/public/whatsapp/interakt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VendorSignupRoute: typeof VendorSignupRoute
  ApiPublicBiometricPunchRoute: typeof ApiPublicBiometricPunchRoute
  ApiPublicWhatsappInteraktRoute: typeof ApiPublicWhatsappInteraktRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-signup': {
      id: '/vendor-signup'
      path: '/vendor-signup'
      fullPath: '/vendor-signup'
      preLoaderRoute: typeof VendorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor': {
      id: '/_app/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AppVendorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tally-import': {
      id: '/_app/tally-import'
      path: '/tally-import'
      fullPath: '/tally-import'
      preLoaderRoute: typeof AppTallyImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders': {
      id: '/_app/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payslips': {
      id: '/_app/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AppPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gst': {
      id: '/_app/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof AppGstRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communications': {
      id: '/_app/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boq': {
      id: '/_app/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof AppBoqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banking': {
      id: '/_app/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AppBankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/': {
      id: '/_app/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AppVendorIndexRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/communications/': {
      id: '/_app/communications/'
      path: '/'
      fullPath: '/communications/'
      preLoaderRoute: typeof AppCommunicationsIndexRouteImport
      parentRoute: typeof AppCommunicationsRoute
    }
    '/_app/vendor/purchase-orders': {
      id: '/_app/vendor/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/vendor/purchase-orders'
      preLoaderRoute: typeof AppVendorPurchaseOrdersRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/vendor/ledger': {
      id: '/_app/vendor/ledger'
      path: '/ledger'
      fullPath: '/vendor/ledger'
      preLoaderRoute: typeof AppVendorLedgerRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/inventory/valuation': {
      id: '/_app/inventory/valuation'
      path: '/valuation'
      fullPath: '/inventory/valuation'
      preLoaderRoute: typeof AppInventoryValuationRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/summary': {
      id: '/_app/inventory/summary'
      path: '/summary'
      fullPath: '/inventory/summary'
      preLoaderRoute: typeof AppInventorySummaryRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/reorder': {
      id: '/_app/inventory/reorder'
      path: '/reorder'
      fullPath: '/inventory/reorder'
      preLoaderRoute: typeof AppInventoryReorderRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/movements': {
      id: '/_app/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/journals': {
      id: '/_app/inventory/journals'
      path: '/journals'
      fullPath: '/inventory/journals'
      preLoaderRoute: typeof AppInventoryJournalsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/items': {
      id: '/_app/inventory/items'
      path: '/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof AppInventoryItemsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/godowns': {
      id: '/_app/inventory/godowns'
      path: '/godowns'
      fullPath: '/inventory/godowns'
      preLoaderRoute: typeof AppInventoryGodownsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/gst/returns': {
      id: '/_app/gst/returns'
      path: '/returns'
      fullPath: '/gst/returns'
      preLoaderRoute: typeof AppGstReturnsRouteImport
      parentRoute: typeof AppGstRoute
    }
    '/_app/gst/hsn': {
      id: '/_app/gst/hsn'
      path: '/hsn'
      fullPath: '/gst/hsn'
      preLoaderRoute: typeof AppGstHsnRouteImport
      parentRoute: typeof AppGstRoute
    }
    '/_app/gst/einvoices': {
      id: '/_app/gst/einvoices'
      path: '/einvoices'
      fullPath: '/gst/einvoices'
      preLoaderRoute: typeof AppGstEinvoicesRouteImport
      parentRoute: typeof AppGstRoute
    }
    '/_app/communications/whatsapp-logs': {
      id: '/_app/communications/whatsapp-logs'
      path: '/whatsapp-logs'
      fullPath: '/communications/whatsapp-logs'
      preLoaderRoute: typeof AppCommunicationsWhatsappLogsRouteImport
      parentRoute: typeof AppCommunicationsRoute
    }
    '/_app/communications/templates': {
      id: '/_app/communications/templates'
      path: '/templates'
      fullPath: '/communications/templates'
      preLoaderRoute: typeof AppCommunicationsTemplatesRouteImport
      parentRoute: typeof AppCommunicationsRoute
    }
    '/_app/communications/providers': {
      id: '/_app/communications/providers'
      path: '/providers'
      fullPath: '/communications/providers'
      preLoaderRoute: typeof AppCommunicationsProvidersRouteImport
      parentRoute: typeof AppCommunicationsRoute
    }
    '/_app/banking/reconcile': {
      id: '/_app/banking/reconcile'
      path: '/reconcile'
      fullPath: '/banking/reconcile'
      preLoaderRoute: typeof AppBankingReconcileRouteImport
      parentRoute: typeof AppBankingRoute
    }
    '/_app/banking/payment-advice': {
      id: '/_app/banking/payment-advice'
      path: '/payment-advice'
      fullPath: '/banking/payment-advice'
      preLoaderRoute: typeof AppBankingPaymentAdviceRouteImport
      parentRoute: typeof AppBankingRoute
    }
    '/_app/banking/currencies': {
      id: '/_app/banking/currencies'
      path: '/currencies'
      fullPath: '/banking/currencies'
      preLoaderRoute: typeof AppBankingCurrenciesRouteImport
      parentRoute: typeof AppBankingRoute
    }
    '/_app/banking/cheques': {
      id: '/_app/banking/cheques'
      path: '/cheques'
      fullPath: '/banking/cheques'
      preLoaderRoute: typeof AppBankingChequesRouteImport
      parentRoute: typeof AppBankingRoute
    }
    '/_app/banking/accounts': {
      id: '/_app/banking/accounts'
      path: '/accounts'
      fullPath: '/banking/accounts'
      preLoaderRoute: typeof AppBankingAccountsRouteImport
      parentRoute: typeof AppBankingRoute
    }
    '/_app/accounting/trial-balance': {
      id: '/_app/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AppAccountingTrialBalanceRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/profit-loss': {
      id: '/_app/accounting/profit-loss'
      path: '/profit-loss'
      fullPath: '/accounting/profit-loss'
      preLoaderRoute: typeof AppAccountingProfitLossRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/periods': {
      id: '/_app/accounting/periods'
      path: '/periods'
      fullPath: '/accounting/periods'
      preLoaderRoute: typeof AppAccountingPeriodsRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/ledgers': {
      id: '/_app/accounting/ledgers'
      path: '/ledgers'
      fullPath: '/accounting/ledgers'
      preLoaderRoute: typeof AppAccountingLedgersRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/day-book': {
      id: '/_app/accounting/day-book'
      path: '/day-book'
      fullPath: '/accounting/day-book'
      preLoaderRoute: typeof AppAccountingDayBookRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/balance-sheet': {
      id: '/_app/accounting/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AppAccountingBalanceSheetRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/audit-log': {
      id: '/_app/accounting/audit-log'
      path: '/audit-log'
      fullPath: '/accounting/audit-log'
      preLoaderRoute: typeof AppAccountingAuditLogRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/api/public/whatsapp/interakt': {
      id: '/api/public/whatsapp/interakt'
      path: '/api/public/whatsapp/interakt'
      fullPath: '/api/public/whatsapp/interakt'
      preLoaderRoute: typeof ApiPublicWhatsappInteraktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/biometric/punch': {
      id: '/api/public/biometric/punch'
      path: '/api/public/biometric/punch'
      fullPath: '/api/public/biometric/punch'
      preLoaderRoute: typeof ApiPublicBiometricPunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendor/purchase-orders/$id': {
      id: '/_app/vendor/purchase-orders/$id'
      path: '/$id'
      fullPath: '/vendor/purchase-orders/$id'
      preLoaderRoute: typeof AppVendorPurchaseOrdersIdRouteImport
      parentRoute: typeof AppVendorPurchaseOrdersRoute
    }
    '/_app/print/supplier-ledger/$id': {
      id: '/_app/print/supplier-ledger/$id'
      path: '/print/supplier-ledger/$id'
      fullPath: '/print/supplier-ledger/$id'
      preLoaderRoute: typeof AppPrintSupplierLedgerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print/purchase/$id': {
      id: '/_app/print/purchase/$id'
      path: '/print/purchase/$id'
      fullPath: '/print/purchase/$id'
      preLoaderRoute: typeof AppPrintPurchaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print/party-ledger/$id': {
      id: '/_app/print/party-ledger/$id'
      path: '/print/party-ledger/$id'
      fullPath: '/print/party-ledger/$id'
      preLoaderRoute: typeof AppPrintPartyLedgerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print/invoice/$id': {
      id: '/_app/print/invoice/$id'
      path: '/print/invoice/$id'
      fullPath: '/print/invoice/$id'
      preLoaderRoute: typeof AppPrintInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gst/returns/$id': {
      id: '/_app/gst/returns/$id'
      path: '/$id'
      fullPath: '/gst/returns/$id'
      preLoaderRoute: typeof AppGstReturnsIdRouteImport
      parentRoute: typeof AppGstReturnsRoute
    }
    '/_app/banking/reconcile/$id': {
      id: '/_app/banking/reconcile/$id'
      path: '/$id'
      fullPath: '/banking/reconcile/$id'
      preLoaderRoute: typeof AppBankingReconcileIdRouteImport
      parentRoute: typeof AppBankingReconcileRoute
    }
    '/_app/banking/cheque-print/$id': {
      id: '/_app/banking/cheque-print/$id'
      path: '/cheque-print/$id'
      fullPath: '/banking/cheque-print/$id'
      preLoaderRoute: typeof AppBankingChequePrintIdRouteImport
      parentRoute: typeof AppBankingRoute
    }
    '/_app/accounting/vouchers/new': {
      id: '/_app/accounting/vouchers/new'
      path: '/vouchers/new'
      fullPath: '/accounting/vouchers/new'
      preLoaderRoute: typeof AppAccountingVouchersNewRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/voucher/$id': {
      id: '/_app/accounting/voucher/$id'
      path: '/voucher/$id'
      fullPath: '/accounting/voucher/$id'
      preLoaderRoute: typeof AppAccountingVoucherIdRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/accounting/ledger/$id': {
      id: '/_app/accounting/ledger/$id'
      path: '/ledger/$id'
      fullPath: '/accounting/ledger/$id'
      preLoaderRoute: typeof AppAccountingLedgerIdRouteImport
      parentRoute: typeof AppAccountingRoute
    }
  }
}

interface AppAccountingRouteChildren {
  AppAccountingAuditLogRoute: typeof AppAccountingAuditLogRoute
  AppAccountingBalanceSheetRoute: typeof AppAccountingBalanceSheetRoute
  AppAccountingDayBookRoute: typeof AppAccountingDayBookRoute
  AppAccountingLedgersRoute: typeof AppAccountingLedgersRoute
  AppAccountingPeriodsRoute: typeof AppAccountingPeriodsRoute
  AppAccountingProfitLossRoute: typeof AppAccountingProfitLossRoute
  AppAccountingTrialBalanceRoute: typeof AppAccountingTrialBalanceRoute
  AppAccountingLedgerIdRoute: typeof AppAccountingLedgerIdRoute
  AppAccountingVoucherIdRoute: typeof AppAccountingVoucherIdRoute
  AppAccountingVouchersNewRoute: typeof AppAccountingVouchersNewRoute
}

const AppAccountingRouteChildren: AppAccountingRouteChildren = {
  AppAccountingAuditLogRoute: AppAccountingAuditLogRoute,
  AppAccountingBalanceSheetRoute: AppAccountingBalanceSheetRoute,
  AppAccountingDayBookRoute: AppAccountingDayBookRoute,
  AppAccountingLedgersRoute: AppAccountingLedgersRoute,
  AppAccountingPeriodsRoute: AppAccountingPeriodsRoute,
  AppAccountingProfitLossRoute: AppAccountingProfitLossRoute,
  AppAccountingTrialBalanceRoute: AppAccountingTrialBalanceRoute,
  AppAccountingLedgerIdRoute: AppAccountingLedgerIdRoute,
  AppAccountingVoucherIdRoute: AppAccountingVoucherIdRoute,
  AppAccountingVouchersNewRoute: AppAccountingVouchersNewRoute,
}

const AppAccountingRouteWithChildren = AppAccountingRoute._addFileChildren(
  AppAccountingRouteChildren,
)

interface AppBankingReconcileRouteChildren {
  AppBankingReconcileIdRoute: typeof AppBankingReconcileIdRoute
}

const AppBankingReconcileRouteChildren: AppBankingReconcileRouteChildren = {
  AppBankingReconcileIdRoute: AppBankingReconcileIdRoute,
}

const AppBankingReconcileRouteWithChildren =
  AppBankingReconcileRoute._addFileChildren(AppBankingReconcileRouteChildren)

interface AppBankingRouteChildren {
  AppBankingAccountsRoute: typeof AppBankingAccountsRoute
  AppBankingChequesRoute: typeof AppBankingChequesRoute
  AppBankingCurrenciesRoute: typeof AppBankingCurrenciesRoute
  AppBankingPaymentAdviceRoute: typeof AppBankingPaymentAdviceRoute
  AppBankingReconcileRoute: typeof AppBankingReconcileRouteWithChildren
  AppBankingChequePrintIdRoute: typeof AppBankingChequePrintIdRoute
}

const AppBankingRouteChildren: AppBankingRouteChildren = {
  AppBankingAccountsRoute: AppBankingAccountsRoute,
  AppBankingChequesRoute: AppBankingChequesRoute,
  AppBankingCurrenciesRoute: AppBankingCurrenciesRoute,
  AppBankingPaymentAdviceRoute: AppBankingPaymentAdviceRoute,
  AppBankingReconcileRoute: AppBankingReconcileRouteWithChildren,
  AppBankingChequePrintIdRoute: AppBankingChequePrintIdRoute,
}

const AppBankingRouteWithChildren = AppBankingRoute._addFileChildren(
  AppBankingRouteChildren,
)

interface AppCommunicationsRouteChildren {
  AppCommunicationsProvidersRoute: typeof AppCommunicationsProvidersRoute
  AppCommunicationsTemplatesRoute: typeof AppCommunicationsTemplatesRoute
  AppCommunicationsWhatsappLogsRoute: typeof AppCommunicationsWhatsappLogsRoute
  AppCommunicationsIndexRoute: typeof AppCommunicationsIndexRoute
}

const AppCommunicationsRouteChildren: AppCommunicationsRouteChildren = {
  AppCommunicationsProvidersRoute: AppCommunicationsProvidersRoute,
  AppCommunicationsTemplatesRoute: AppCommunicationsTemplatesRoute,
  AppCommunicationsWhatsappLogsRoute: AppCommunicationsWhatsappLogsRoute,
  AppCommunicationsIndexRoute: AppCommunicationsIndexRoute,
}

const AppCommunicationsRouteWithChildren =
  AppCommunicationsRoute._addFileChildren(AppCommunicationsRouteChildren)

interface AppGstReturnsRouteChildren {
  AppGstReturnsIdRoute: typeof AppGstReturnsIdRoute
}

const AppGstReturnsRouteChildren: AppGstReturnsRouteChildren = {
  AppGstReturnsIdRoute: AppGstReturnsIdRoute,
}

const AppGstReturnsRouteWithChildren = AppGstReturnsRoute._addFileChildren(
  AppGstReturnsRouteChildren,
)

interface AppGstRouteChildren {
  AppGstEinvoicesRoute: typeof AppGstEinvoicesRoute
  AppGstHsnRoute: typeof AppGstHsnRoute
  AppGstReturnsRoute: typeof AppGstReturnsRouteWithChildren
}

const AppGstRouteChildren: AppGstRouteChildren = {
  AppGstEinvoicesRoute: AppGstEinvoicesRoute,
  AppGstHsnRoute: AppGstHsnRoute,
  AppGstReturnsRoute: AppGstReturnsRouteWithChildren,
}

const AppGstRouteWithChildren =
  AppGstRoute._addFileChildren(AppGstRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryGodownsRoute: typeof AppInventoryGodownsRoute
  AppInventoryItemsRoute: typeof AppInventoryItemsRoute
  AppInventoryJournalsRoute: typeof AppInventoryJournalsRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryReorderRoute: typeof AppInventoryReorderRoute
  AppInventorySummaryRoute: typeof AppInventorySummaryRoute
  AppInventoryValuationRoute: typeof AppInventoryValuationRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryGodownsRoute: AppInventoryGodownsRoute,
  AppInventoryItemsRoute: AppInventoryItemsRoute,
  AppInventoryJournalsRoute: AppInventoryJournalsRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryReorderRoute: AppInventoryReorderRoute,
  AppInventorySummaryRoute: AppInventorySummaryRoute,
  AppInventoryValuationRoute: AppInventoryValuationRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppVendorPurchaseOrdersRouteChildren {
  AppVendorPurchaseOrdersIdRoute: typeof AppVendorPurchaseOrdersIdRoute
}

const AppVendorPurchaseOrdersRouteChildren: AppVendorPurchaseOrdersRouteChildren =
  {
    AppVendorPurchaseOrdersIdRoute: AppVendorPurchaseOrdersIdRoute,
  }

const AppVendorPurchaseOrdersRouteWithChildren =
  AppVendorPurchaseOrdersRoute._addFileChildren(
    AppVendorPurchaseOrdersRouteChildren,
  )

interface AppVendorRouteChildren {
  AppVendorLedgerRoute: typeof AppVendorLedgerRoute
  AppVendorPurchaseOrdersRoute: typeof AppVendorPurchaseOrdersRouteWithChildren
  AppVendorIndexRoute: typeof AppVendorIndexRoute
}

const AppVendorRouteChildren: AppVendorRouteChildren = {
  AppVendorLedgerRoute: AppVendorLedgerRoute,
  AppVendorPurchaseOrdersRoute: AppVendorPurchaseOrdersRouteWithChildren,
  AppVendorIndexRoute: AppVendorIndexRoute,
}

const AppVendorRouteWithChildren = AppVendorRoute._addFileChildren(
  AppVendorRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBankingRoute: typeof AppBankingRouteWithChildren
  AppBoqRoute: typeof AppBoqRoute
  AppCommunicationsRoute: typeof AppCommunicationsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppGstRoute: typeof AppGstRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppPayslipsRoute: typeof AppPayslipsRoute
  AppProductionRoute: typeof AppProductionRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTallyImportRoute: typeof AppTallyImportRoute
  AppVendorRoute: typeof AppVendorRouteWithChildren
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppPrintInvoiceIdRoute: typeof AppPrintInvoiceIdRoute
  AppPrintPartyLedgerIdRoute: typeof AppPrintPartyLedgerIdRoute
  AppPrintPurchaseIdRoute: typeof AppPrintPurchaseIdRoute
  AppPrintSupplierLedgerIdRoute: typeof AppPrintSupplierLedgerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBankingRoute: AppBankingRouteWithChildren,
  AppBoqRoute: AppBoqRoute,
  AppCommunicationsRoute: AppCommunicationsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppGstRoute: AppGstRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppPayslipsRoute: AppPayslipsRoute,
  AppProductionRoute: AppProductionRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTallyImportRoute: AppTallyImportRoute,
  AppVendorRoute: AppVendorRouteWithChildren,
  AppWhatsappRoute: AppWhatsappRoute,
  AppPrintInvoiceIdRoute: AppPrintInvoiceIdRoute,
  AppPrintPartyLedgerIdRoute: AppPrintPartyLedgerIdRoute,
  AppPrintPurchaseIdRoute: AppPrintPurchaseIdRoute,
  AppPrintSupplierLedgerIdRoute: AppPrintSupplierLedgerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VendorSignupRoute: VendorSignupRoute,
  ApiPublicBiometricPunchRoute: ApiPublicBiometricPunchRoute,
  ApiPublicWhatsappInteraktRoute: ApiPublicWhatsappInteraktRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
