BEGIN;

-- In-app notifications are server-generated. A user may only read/mark their own.
REVOKE INSERT, DELETE ON public.in_app_notifications FROM authenticated;
DROP POLICY IF EXISTS "ian read own" ON public.in_app_notifications;
DROP POLICY IF EXISTS "ian update own" ON public.in_app_notifications;
DROP POLICY IF EXISTS "ian admin read" ON public.in_app_notifications;
DROP POLICY IF EXISTS "ian insert authenticated" ON public.in_app_notifications;
CREATE POLICY "ian read own"
  ON public.in_app_notifications
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());
CREATE POLICY "ian update own"
  ON public.in_app_notifications
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Voucher audit rows are generated by protected database triggers. Clients must
-- never fabricate audit records, and users may only read audits from the active book.
REVOKE INSERT ON public.voucher_audit_log FROM authenticated;
DROP POLICY IF EXISTS "audit insert" ON public.voucher_audit_log;
DROP POLICY IF EXISTS "voucher audit active company" ON public.voucher_audit_log;
CREATE POLICY "voucher audit active company"
  ON public.voucher_audit_log AS RESTRICTIVE
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.vouchers v
      WHERE v.id = voucher_audit_log.voucher_id
        AND v.company_id = public.current_company_id()
        AND public.has_company_access(v.company_id)
    )
  );

COMMIT;
